export const NAVIGATION_NAMES = {
  ACCOUNT: "account",
  ACCOUNT_HOME: "account_home",
  ACCOUNT_LOGIN: "account_login",
  ACCOUNT_SIGN_UP: "account_sign_up",
  ONBOARDING: "onboarding",
  HOME: "home",
  RESTAURANTS: "Restaurants",
  RESTAURANTS_HOME: "restaurants_home",
  RESTAURANTS_DETAIL: "restaurants_details",
  CHECKOUT: "Checkout",
  CHECKOUT_HOME: "checkout_home",
  CHECKOUT_SUCCESS: "checkout_success",
  CHECKOUT_ERROR: "checkout_error",
  MAP: "Map",
  MAP_HOME: "map_home",
  SETTINGS: "Settings",
  SETTINGS_HOME: "settings_home",
  SETTINGS_FAVORITES: "settings_favorites",
  SETTINGS_CAMERA: "settings_camera",
};
